default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play Internal Testing"
  lane :beta do
    # 1. Version bump
    sh("cd ../.. && npm run bump")

    # 2. Build App Bundle
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )

    # 3. Upload to Google Play (Optional - needs JSON key)
    # upload_to_play_store(track: 'internal')
  end

  desc "Build APK"
  lane :build_apk do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end
end
